// Copyright (C) 2021 CGI France
//
// This file is part of PIMO.
//
// PIMO is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// PIMO is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with PIMO.  If not, see <http://www.gnu.org/licenses/>.

package maskingdata

var NameDEM = []string{
	"Peter",
	"Michael",
	"Wolfgang",
	"Thomas",
	"Klaus",
	"Werner",
	"Manfred",
	"Hans",
	"Heinz",
	"Andreas",
	"Jürgen",
	"Helmut",
	"Gerhard",
	"Günter",
	"Hermann",
	"Karl",
	"Rainer",
	"Fritz",
	"Walter",
	"Rolf",
	"Kurt",
	"Siegfried",
	"Joachim",
	"Johann",
	"Ralf",
	"Norbert",
	"Wilhelm",
	"Bernhard",
	"Markus",
	"Jörg",
	"Alfred",
	"Matthias",
	"Alexander",
	"Ulrich",
	"Willi",
	"Erich",
	"Harald",
	"Roland",
	"Reinhard",
	"Paul",
	"Günther",
	"Gerd",
	"Lothar",
	"Ernst",
	"Robert",
	"Dirk",
	"Friedrich",
	"Erwin",
	"Johannes",
	"Otto",
	"Jens",
	"Volker",
	"Wilfried",
	"Holger",
	"Hans-Jürgen",
	"Richard",
	"Hubert",
	"Anton",
	"Udo",
	"Dietmar",
	"Hartmut",
	"Christoph",
	"Oliver",
	"Stephan",
	"Hans-Joachim",
	"Albert",
	"Daniel",
	"Ludwig",
	"Reinhold",
	"Detlef",
	"Adolf",
	"Sven",
	"Reiner",
	"Steffen",
	"Eberhard",
	"Torsten",
	"Heiko",
	"Sebastian",
	"Kai",
	"Jan",
	"Mario",
	"Lukas",
	"Jonas",
	"Jakob",
	"Emil",
	"Lucas",
	"Noah",
	"Liam",
	"Ben",
	"Finn",
	"Elias",
	"David",
	"Moritz",
	"Felix",
	"Luke",
	"Stefan",
	"Tobias",
	"Florian",
	"Leon",
	"Lars",
}