// Copyright (C) 2021 CGI France
//
// This file is part of PIMO.
//
// PIMO is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// PIMO is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with PIMO.  If not, see <http://www.gnu.org/licenses/>.

package maskingdata

var NameESM = []string{
	"Aarón",
	"Abel",
	"Abelardo",
	"Abraham",
	"Adalberto",
	"Adán",
	"Adrián",
	"Agustín",
	"Alberto",
	"Alejandro",
	"Alejo",
	"Alfonso",
	"Alfredo",
	"Alonso",
	"Álvaro",
	"Amaro",
	"Ambrosio",
	"Anastasio",
	"Andrés",
	"Ángel",
	"Anselmo",
	"Antonio",
	"Aquiles",
	"Armando",
	"Arturo",
	"Baldomero",
	"Baltasar",
	"Bartolomé",
	"Basilio",
	"Bautista",
	"Benjamín",
	"Benito",
	"Bernardo",
	"Blas",
	"Bonifacio",
	"Bruno",
	"Buenaventura",
	"Camilo",
	"Carlos",
	"Carmelo",
	"Casimiro",
	"Cayetano",
	"Celedonio",
	"Celso",
	"Cipriano",
	"Cirilo",
	"Clemente",
	"Crisóstomo",
	"Cristian",
	"Cristóbal",
	"Claudio",
	"Dagoberto",
	"Damián",
	"Daniel",
	"Darío",
	"David",
	"Demetrio",
	"Diego",
	"Dionisio",
	"Domingo",
	"Efraín",
	"Eleuterio",
	"Elías",
	"Eloy",
	"Emilio",
	"Eneas",
	"Enrique",
	"Epifanio",
	"Erasmo",
	"Ernesto",
	"Esteban",
	"Eugenio",
	"Eusebio",
	"Evaristo",
	"Ezequiel",
	"Fabián",
	"Facundo",
	"Fausto",
	"Federico",
	"Feliciano",
	"Felipe",
	"Félix",
	"Fernando",
	"Fidel",
	"Filemón",
	"Filiberto",
	"Firmo",
	"Flavio",
	"Florencio",
	"Fortunato",
	"Francisco",
	"Froilán",
	"Frumencio",
	"Gabino",
	"Gabriel",
	"Gael",
	"Gaspar",
	"Gastón",
	"Gerardo",
}
