// Copyright (C) 2021 CGI France
//
// This file is part of PIMO.
//
// PIMO is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// PIMO is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with PIMO.  If not, see <http://www.gnu.org/licenses/>.

package maskingdata

var NameESF = []string{
	"Adriana",
	"Aitana",
	"Alejandra",
	"Alexia",
	"Alicia",
	"Alma",
	"Amalia",
	"Ana",
	"Andrea",
	"Ángela",
	"Ángeles",
	"Antonia",
	"Araceli",
	"Ariadna",
	"Aurora",
	"Beatriz",
	"Begoña",
	"Belén",
	"Blanca",
	"Candela",
	"Carla",
	"Carlota",
	"Carmen",
	"Carolina",
	"Catalina",
	"Cayetana",
	"Celia",
	"Clara",
	"Claudia",
	"Concepción",
	"Cristina",
	"Daniela",
	"Dolores",
	"Elena",
	"Elisa",
	"Elsa",
	"Emilia",
	"Encarnación",
	"Esperanza",
	"Estrella",
	"Eugenia",
	"Eva",
	"Fabiola",
	"Fátima",
	"Francisca",
	"Gabriela",
	"Gloria",
	"Inés",
	"Irene",
	"Isabel",
	"Isabella",
	"Jimena",
	"Josefa",
	"Juana",
	"Julia",
	"Laura",
	"Leyre",
	"Lola",
	"Lucía",
	"Luciana",
	"Luisa",
	"Luna",
	"Luz",
	"Macarena",
	"Manuela",
	"Marcela",
	"María",
	"Mariana",
	"Marina",
	"Marisol",
	"Marta",
	"Martina",
	"Mercedes",
	"Micaela",
	"Milagros",
	"Mía",
	"Mireia",
	"Miriam",
	"Natalia",
	"Nieves",
	"Noelia",
	"Nuria",
	"Olivia",
	"Paloma",
	"Paula",
	"Pilar",
	"Rafaela",
	"Regina",
	"Renata",
	"Rocío",
	"Rosa",
	"Rosario",
	"Sara",
	"Silvia",
	"Sofía",
	"Teresa",
	"Valentina",
	"Valeria",
	"Victoria",
	"Ximena",
}
