// Copyright (C) 2021 CGI France
//
// This file is part of PIMO.
//
// PIMO is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// PIMO is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with PIMO.  If not, see <http://www.gnu.org/licenses/>.

package maskingdata

var NameDEF = []string{
	"Ursula",
	"Maria",
	"Monika",
	"Petra",
	"Renate",
	"Helga",
	"Angelika",
	"Doris",
	"Irmgard",
	"Hannelore",
	"Gertrud",
	"Ulrike",
	"Kerstin",
	"Jutta",
	"Ruth",
	"Anja",
	"Gerda",
	"Sandra",
	"Christel",
	"Elfriede",
	"Rita",
	"Anneliese",
	"Waltraud",
	"Ilse",
	"Nicole",
	"Beate",
	"Regina",
	"Ingeborg",
	"Rosemarie",
	"Gabriele",
	"Manuela",
	"Silke",
	"Sonja",
	"Katharina",
	"Gudrun",
	"Anita",
	"Tanja",
	"Christiame",
	"Sigrid",
	"Silvia",
	"Bärbel",
	"Bettina",
	"Daniela",
	"Irene",
	"Simone",
	"Cornelia",
	"Stefanie",
	"Annette",
	"Anke",
	"Heidi",
	"Angela",
	"Michaela",
	"Dagmar",
	"Johanna",
	"Melanie",
	"Katrin",
	"Roswitha",
	"Annemarie",
	"Sylvia",
	"Erna",
	"Margot",
	"Iris",
	"Alexandra",
	"Katja",
	"Margarete",
	"Astrid",
	"Anne",
	"Margit",
	"Helene",
	"Julia",
	"Carmen",
	"Ilona",
	"Hedwig",
	"Emily",
	"Sofia",
	"Marie",
	"Mia",
	"Emma",
	"Hanna",
	"Ella",
	"Lina",
	"Lea",
	"Mila",
	"Lara",
	"Emilia",
	"Anna",
	"Sophia",
	"Zoe",
	"Hannah",
	"Charlotte",
	"Sophie",
	"Leah",
	"Elisa",
	"Nora",
	"Ava",
	"Lia",
	"Eva",
	"Clara",
	"Lily",
	"Luisa",
}
