// Copyright (C) 2021 CGI France
//
// This file is part of PIMO.
//
// PIMO is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// PIMO is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with PIMO.  If not, see <http://www.gnu.org/licenses/>.

package maskingdata

var SurnameFR = []string{
	"Martin",
	"Bernard",
	"Dubois",
	"Thomas",
	"Robert",
	"Richard",
	"Petit",
	"Durand",
	"Leroy",
	"Moreau",
	"Simon",
	"Laurent",
	"Lefebvre",
	"Michel",
	"Garcia",
	"David",
	"Bertrand",
	"Roux",
	"Vincent",
	"Fournier",
	"Morel",
	"Girard",
	"Andre",
	"Lefevre",
	"Mercier",
	"Dupont",
	"Lambert",
	"Bonnet",
	"Francois",
	"Martinez",
	"Legrand",
	"Garnier",
	"Faure",
	"Rousseau",
	"Blanc",
	"Guerin",
	"Muller",
	"Henry",
	"Roussel",
	"Nicolas",
	"Perrin",
	"Morin",
	"Mathieu",
	"Clement",
	"Gauthier",
	"Dumont",
	"Lopez",
	"Fontaine",
	"Chevalier",
	"Robin",
	"Masson",
	"Sanchez",
	"Gerard",
	"Nguyen",
	"Boyer",
	"Denis",
	"Lemaire",
	"Duval",
	"Joly",
	"Gautier",
	"Roger",
	"Roche",
	"Roy",
	"Noel",
	"Meyer",
	"Lucas",
	"Meunier",
	"Jean",
	"Perez",
	"Marchand",
	"Dufour",
	"Blanchard",
	"Marie",
	"Barbier",
	"Brun",
	"Dumas",
	"Brunet",
	"Schmitt",
	"Leroux",
	"Colin",
	"Fernandez",
	"Pierre",
	"Renard",
	"Arnaud",
	"Rolland",
	"Caron",
	"Aubert",
	"Giraud",
	"Leclerc",
	"Vidal",
	"Bourgeois",
	"Renaud",
	"Lemoine",
	"Picard",
	"Gaillard",
	"Philippe",
	"Leclercq",
	"Lacroix",
	"Fabre",
	"Dupuis",
}
