// Copyright (C) 2021 CGI France
//
// This file is part of PIMO.
//
// PIMO is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// PIMO is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with PIMO.  If not, see <http://www.gnu.org/licenses/>.

package maskingdata

var SurnameDE = []string{
	"Müller",
	"Schmidt",
	"Schneider",
	"Fischer",
	"Weber",
	"Meyer",
	"Wagner",
	"Becker",
	"Schulz",
	"Hoffmann",
	"Koch",
	"Richter",
	"Bauer",
	"Schäfer",
	"Klein",
	"Wolf",
	"Schröder",
	"Neumann",
	"Schwarz",
	"Braun",
	"Zimmermann",
	"Hofmann",
	"Lange",
	"Hartmann",
	"Krüger",
	"Krause",
	"Lehmann",
	"Schmitz",
	"Meier",
	"Schmitt",
	"Werner",
	"Schmid",
	"Schulze",
	"Maier",
	"Herrmann",
	"Mayer",
	"Köhler",
	"Walter",
	"König",
	"Huber",
	"Kaiser",
	"Peters",
	"Fuchs",
	"Möller",
	"Lang",
	"Scholz",
	"Jung",
	"Weiß",
	"Hahn",
	"Keller",
	"Berger",
	"Vogel",
	"Schubert",
	"Friedrich",
	"Frank",
	"Roth",
	"Winkler",
	"Beck",
	"Günther",
	"Lorenz",
	"Baumann",
	"Franke",
	"Albrecht",
	"Ludwig",
	"Winter",
	"Simon",
	"Schuster",
	"Schumacher",
	"Kraus",
	"Böhm",
	"Vogt",
	"Martin",
	"Stein",
	"Jäger",
	"Sommer",
	"Krämer",
	"Brandt",
	"Otto",
	"Heinrich",
	"Schulte",
	"Graf",
	"Haas",
	"Seidel",
	"Schreiber",
	"Groß",
	"Dietrich",
	"Engel",
	"Ziegler",
	"Horn",
	"Bergmann",
	"Pohl",
	"Kuhn",
	"Jansen",
	"Voigt",
	"Kühn",
	"Beyer",
	"Busch",
	"Thomas",
	"Hansen",
	"Lindner",
}
