#!/bin/bash
# Copyright (C) 2021 CGI France
# 
# This file is part of PIMO.
# 
# PIMO is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# PIMO is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with PIMO.  If not, see <http://www.gnu.org/licenses/>.

set -e
if git status --porcelain | grep "^.M" > /dev/null
then
    echo "🚽 Add or stash unstaged changes before commit"
    exit 1
else
    echo "👌 Nothing to stash"
fi
make lint test venom
