version: "3.7"

services:
  vscode:
    build:
      context: .
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    volumes:
      - ../:/workspace
      - ~/.ssh:/home/vscode/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=
      - NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    entrypoint: tail -f /dev/null
