# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: docker-compose -f .devcontainer/docker-compose.yml build

      - name: Start services
        run: docker-compose -f .devcontainer/docker-compose.yml up -d vscode

      - name: Init env
        run: docker-compose -f .devcontainer/docker-compose.yml exec -T -u root -w /workspace vscode make init

      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Run CI # up to test-int (info → refresh → lint → test → release → test-int)
        run: |
          docker-compose -f .devcontainer/docker-compose.yml exec \
            -T \
            -u root \
            -w /workspace \
            -e PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/home/vscode/go/bin:/workspace/bin \
            vscode \
            neon -props "{tag: ${CI_ACTION_REF_NAME}, MODULE: github.com/${CI_REPOSITORY,,}, BY: $(echo ${CI_ACTOR} | tr -d '[]')}" test-int
